---
- name: Acesso ao servidor
  hosts: 'ip ou hostname do servidor que deseja instalar o agente'
  vars:
    srv: 'ip do server zabbix'
    hst: "{{ hostvars[inventory_hostname]['ansible_hostname']}}"
  tasks:
    # baixando repositorio oficial do zabbix agente usando o wget
    - name: Dowload repositorio zabbix.deb
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
        dest: /home/higor/
    # instalando repositorio zabbix usando o comando dpkg
    - name: Install zabbix-agent
      become: true
      command: dpkg -i /home/higor/zabbix-release_6.4-1+ubuntu22.04_all.deb
    # utualizar todos os pacotes para uma versão mais recente 
    - name: Update all package
      become: true
      apt:
        update_cache: true
    # instalando zabbix agent
    - name: Apt install zabbix-agent
      become: true
      apt:
        name: Zabbix-agent
        state: present
        update_cache: true
    # Editar o arquivo zabbix_agentd.conf alterar o Hostname o ip do Server e ServerActive
    - name: Template ip server file zabbix_agentd.conf
      become: true
      ansible.builtin.template:
        src: /etc/ansible/roles/templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
